config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  scope '/', defaults: { format: :html }, constraints: { format: :html } do
    delete 'users/stop_masquerading'
    resources :users, except: [:new] do
      post 'masquerade'
    end
    resources :groups
    resources :messages, only: :index
    resources :roles

    post 'payment_processor/paypal' => 'payment_processor#paypal'
    resources :payments, only: [:new, :create, :show, :index]
    get 'login' => 'login#index'
    post 'login' => 'login#verify'
    delete 'login' => 'login#logout'
  end

  scope :api, defaults: { format: :json }, constraints: { format: :json } do
    scope :v1 do
      resources :group_memberships, only: [:destroy, :create, :update]
      resources :users, except: [:new, :edit] do
        get 'group_memberships' => 'users#group_memberships'
      end
      get 'messages/recipients' => 'messages#search_recipients'
      resources :messages, except: [:new, :edit]
      resources :groups, except: [:new, :edit] do
        get 'potential_applicants' => 'groups#potential_applicants'
        get 'users' => 'groups#users'
        delete 'users' => 'group_memberships#destroy'
        put 'users' => 'group_memberships#create'
      end
      resources :roles, except: [:new, :edit] do
        get 'users' => 'roles#users'
        resources :role_memberships, only: [:create, :destroy]
      end

      resources :payments, only: [:index]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :login_sessions
  has_many :api_keys
  has_many :group_memberships, -> { active }
  has_many :groups, -> { active }, through: :group_memberships
  has_many :message_participants, -> { active }
  has_many :messages, -> { active }, through: :message_participants
  has_many :role_memberships, -> { active }
  has_many :roles, -> { active }, through: :role_memberships
  has_many :monetary_transactions
  has_many :payments
  has_many :page_views
  has_many :bets

  scope :active, -> { where(state: :active) }
  scope :deleted, -> { where(state: :deleted) }

  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates_presence_of :state
  validates_uniqueness_of :braintree_customer_id

  before_validation :infer_values

  def infer_values
    self.state ||= :active
    self.braintree_customer_id ||= SecureRandom.hex 8
    self.balance ||= 0.0
  end

  def all_messages
    message_participants.includes(:message).order(created_at: :desc)
  end

  def active?
    state == 'active'
  end

  def destroy
    self.state = 'deleted'
    group_memberships.destroy_all
    role_memberships.destroy_all
    save
  end

  def has_permission?(perm)
    roles.any? { |r| r.permissions[perm] }
  end

  def update_balance
    self.update balance: monetary_transactions.active.sum(:amount).round(2)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Api::V1::User
  include PaginationHelper
  skip_authorization_check only: [:stop_masquerading]
  skip_load_and_authorize_resource only: [:stop_masquerading]

  before_action :find_user, only: [:show, :edit, :update, :destroy, :masquerade]
  before_action :find_users, only: [:index]

  load_and_authorize_resource

  def index
    @users = User.active
    if params[:search_term]
      t = params[:search_term]
      @users = @users.where('username LIKE ? OR display_name LIKE ? OR email LIKE ?', "%#{t}%", "%#{t}%", "%#{t}%")
    end
    respond_to do |format|
      format.json do
        render json: pagination_json(@users, :users_json), status: :ok
      end
      format.html do
        @users = @users.paginate pagination_help
      end
    end
  end

  def update
    respond_to do |format|
      format.html do
        if @user.update user_params
          redirect_to users_path
        else
          render 'edit'
        end
      end
    end
  end

  def find_user
    @user = User.active.find params[:user_id] || params[:id]
  end

  def find_users
    @users = User.active
  end

  def create
    @user = User.new user_params
    respond_to do |format|
      format.html do
        if @user.save
          redirect_to @user
        else
          render 'new'
        end
      end
      format.json do
        if @user.save
          render json: user_json(@user), status: :ok
        else
          render json: { errors: @user.errors }, status: :bad_request
        end
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'User deleted!'
        redirect_to :users
      end
      format.json do
        render nothing: true, status: :no_content
      end
    end
  end

  def masquerade
    authorize! :masquerade, @user
    cookie_type['sports_b_masquerade_user'] = @user.id
    redirect_to request.referer || :root
  end

  def stop_masquerading
    cookie_type.delete 'sports_b_masquerade_user'
    redirect_to request.referer || :root
  end

  private
  def user_params
    params.require(:user).permit(:display_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<script type="text/x-handlebars-template" id="users_show_page">

  <div class="col-md-3">
    <h1>{{display_name}}</h1>
    <h4>{{username}}</h4>
    <h4>{{email}}</h4>
  </div>

  <div class="col-md-3 col-md-offset-2">
    <div class="circular ">
    </div>
  </div>

  <span class="pull-right edit-usr-info">
    <a href="#" data-toggle="modal" data-target="#myUserModal">
      <i class="fa fa-pencil"></i>
    </a>
  </span>
</script>

<div class="row user-base-info">
  <div class="col-md-12 well ">
    <div class="users_show_page">
    </div>
  </div>
</div>

<% if can?(:masquerade, @user) %>
  <%= link_to 'Become', user_masquerade_path(@user), method: :post, class: 'btn btn-info' %>
<% end %>

<!-- Modal -->
<div class="modal fade" name="update-user-modal" id="myUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit User</h4>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_tag url: '#' do |u| %>

            <%= u.text_field :display_name %>
            <%= u.text_field :username %>
            <%= u.text_field :email %>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" >Reset Password</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-warning" id="clear-modal">Clear Modal</button>
        <button type="button" class="btn btn-primary" id="update-user">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Edit This User</h2>
    <%= bootstrap_form_for @user, multipart: true do |u| %>
        <% @u = u %>
        <%= @u.text_field :display_name, label: 'Display Name' %>
        <%= @u.text_field :username, label: 'Username' %>
        <%= @u.text_field :email, label: 'Email' %>
        <%= @u.password_field :password %>
        <%= @u.password_field :password_confirmation %>
        <%= @u.submit :Submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<script type="javascript/x-handlebars-template" id="users_index_page">
  <div class="no-bottom-margin list-group">
    <a href="/users/{{id}}" class="list-group-item">
      <h4 class="list-group-item-heading">{{display_name}}</h4>
      <p class="list-group-item-text">{{created_at}}</p>
    </a>
  </div>
</script>


<h1 style="margin-left: 10%">Users Page</h1>
<div class="row col-md-10 col-md-offset-1">
  <div id="users_table">

  </div>
  <ul class="pagination" style="padding-left: 0px" id="users_pagination"></ul>

  <div>

    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      New User
    </button>
  </div>

</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" name="new-user-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create a User</h4>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_tag url: '#' do |u| %>

            <%= u.text_field :display_name %>
            <%= u.text_field :username %>
            <%= u.text_field :email %>
            <%= u.password_field :password %>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-warning" id="clear-modal">Clear Modal</button>
        <button type="button" class="btn btn-primary" id="create-user">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body…</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<script type="text/x-handlebars-template" id="user-groups-panel" >
    <a href="/groups/{{id}}" class="list-group-item" style="text-align: center;">
      <h2 class="list-group-item-heading">{{name}}</h2>
      <p class="list-group-item-text">{{created_at}}</p>
    </a>
</script>

<script type="text/javascript" id="user-groups-modal">

</script>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= render "sidebar" %>
  </div>
</div>

<div class="row">
  <div class="col-md-5 col-sm-10 col-md-offset-1" >
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="panel-title">Payment Information</span>
        <span class="pull-right edit-pane">
          <i class="fa fa-pencil"></i>
        </span>
      </div>
      <div class="panel-body">

      </div>
    </div>
  </div>

  <div class="col-md-5 col-sm-10 user-group-panel" >
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="panel-title">Group Information</span>
        <span class="pull-right edit-pane">
          <i class="fa fa-plus" data-toggle="modal" data-target="#myGroupEditModal"></i>
        </span>
      </div>
      <div class="panel-body panel-body-groups" >

      </div>

      <div class="list-group">
      </div>

      <div class="panel-footer">
      </div>
    </div>
  </div>
</div>




<!--Group Edit Modal -->
<div class="modal fade" id="myGroupEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= @user.display_name %> Groups</h4>
      </div>
      <div class="modal-body">
        <h2>Add <%= @user.display_name %> to Group</h2>
        <div name="groups-list-div" style="display: none;">
          <select name="groups-list" class="form-control" >
            <% @groups.each_with_index do |g, i| %>
                <option value="<%= g.id %>"  <%= 'selected' if i == 0 %>><%= g.name %></option>
            <% end %>
          </select>
          <button class="btn btn-primary form-control" name="add-group-membership-confirm">Confirm</button>
        </div>
        <h4>
          <%= link_to '#', name: 'add-group-membership' do %>
              <i class="fa fa-plus"></i>
              Add Group
          <% end %>
        </h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>