config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  scope '/', defaults: { format: :html }, constraints: { format: :html } do
    delete 'users/stop_masquerading'
    resources :users, except: [:new] do
      post 'masquerade'
    end
    resources :groups
    resources :messages, only: :index
    resources :roles

    post 'payment_processor/paypal' => 'payment_processor#paypal'
    resources :payments, only: [:new, :create, :show, :index]
    get 'login' => 'login#index'
    post 'login' => 'login#verify'
    delete 'login' => 'login#logout'
  end

  scope :api, defaults: { format: :json }, constraints: { format: :json } do
    scope :v1 do
      resources :group_memberships, only: [:destroy, :create, :update]
      resources :users, except: [:new, :edit] do
        get 'group_memberships' => 'users#group_memberships'
      end
      get 'messages/recipients' => 'messages#search_recipients'
      resources :messages, except: [:new, :edit]
      resources :groups, except: [:new, :edit] do
        get 'potential_applicants' => 'groups#potential_applicants'
        get 'users' => 'groups#users'
        delete 'users' => 'group_memberships#destroy'
        put 'users' => 'group_memberships#create'
      end
      resources :roles, except: [:new, :edit] do
        get 'users' => 'roles#users'
        resources :role_memberships, only: [:create, :destroy]
      end

      resources :payments, only: [:index]
    end
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :monetary_transaction
  belongs_to :user

  VALID_GATEWAYS = [
    'braintree'
  ]

  validates_presence_of :user, on: :create
  validates_presence_of :uuid
  validates_inclusion_of :gateway, in: VALID_GATEWAYS
  validates_inclusion_of :state, in: %w(initiated processed failed)
  validates_numericality_of :amount, greater_than: 0.0, less_than: 10000.0, allow_nil: true

  serialize :parameters, Hash

  scope :failed, -> { where(state: :failed) }
  scope :processed, -> { where(state: :processed) }
  scope :initiated, -> { where(state: :initiated) }

  after_initialize do
    # Failsafe: Mark payments as failed if they remain in an initiated state for more than 2 days
    if created_at && created_at < 2.days.ago && state == 'initiated'
      self.state = 'failed'
      save
    end
  end

  before_validation do
    self.uuid ||= SecureRandom.uuid
    self.state ||= :initiated
    self.gateway ||= 'braintree'
  end

  after_save do
    if self.state == 'processed' && self.monetary_transaction.nil?
      t = MonetaryTransaction.create user: self.user, amount: self.amount, transaction_type: 'payment'
      self.update monetary_transaction: t
    end
  end

  def mark_as_processed!
    update state: 'processed'
  end

  def mark_as_failed!
    update state: 'failed'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include Api::V1::Payment
  include PaginationHelper
  load_and_authorize_resource find_by: :uuid

  PARAMS_FOR_JOB = %w(payment_method_nonce)

  def index
    if api_request?
      @payments = @current_user.payments.order(created_at: :desc)
      @payments = @payments.failed if params[:scope] == 'failed'
      @payments = @payments.initiated if params[:scope] == 'initiated'
      @payments = @payments.processed if params[:scope] == 'processed'
    else
      @payments = []
    end
    includes = params[:include] || []
    respond_to do |format|
      format.json do
        @payments = @payments.includes(:monetary_transaction) if includes.include? 'transaction'
        render json: pagination_json(@payments, :payments_json, includes), status: :ok
      end
      format.html
    end
  end

  def create
    @payment = @current_user.payments.new payment_params
    if @payment.save
      ReceivePaymentJob.perform_later(@payment, params.slice(*PARAMS_FOR_JOB))
      flash[:success] = 'Thank you!  Your funds should appear within a few minutes.'
      redirect_to payment_path @payment.uuid
    else
      flash[:error] = 'Oops, there was a problem processing your request'
      render 'new'
    end
  end

  private
  def payment_params
    params.require(:payment).permit(:amount)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment_template.html.erb
<script type="text/x-handlebars-template" id="payment_row_template">
  <a href="/payments/{{uuid}}" class="list-group-item">
    <div class="row">
      <p class="list-group-item-text">
        <div class="col-md-7">Payment ID: {{uuid}}</div>
        <div class="col-md-2">{{amount}}</div>
        <div class="col-md-3">{{created_at}}</div>
      </p>
    </div>
  </a>
</script>

app/views/payments/index.html.erb
<%= render partial: 'payment_template' %>
<div class="row slight-margins">
  <div class="col-md-12">
    <div role="tabpanel">
      <ul class="nav nav-pills" role="tablist" style="margin-bottom: 20px;">
        <li role="presentation" class="active"><a href="#initiated_payments" aria-controls="home" role="tab" data-toggle="tab">Initiated</a></li>
        <li role="presentation"><a href="#processed_payments" aria-controls="home" role="tab" data-toggle="tab">Processed</a></li>
        <li role="presentation"><a href="#failed_payments" aria-controls="home" role="tab" data-toggle="tab">Failed</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="initiated_payments">
          <i class="fa fa-cog fa-spin fa-2x"></i>
          <div class="list-group"></div>
          <ul class="pagination"></ul>
        </div>
        <div role="tabpanel" class="tab-pane" id="processed_payments">
          <i class="fa fa-cog fa-spin fa-2x"></i>
          <div class="list-group"></div>
          <ul class="pagination"></ul>
        </div>
        <div role="tabpanel" class="tab-pane" id="failed_payments">
          <i class="fa fa-cog fa-spin fa-2x"></i>
          <div class="list-group"></div>
          <ul class="pagination"></ul>
        </div>
      </div>
    </div>
    <div>
      <%= link_to 'New Payment', new_payment_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <%= bootstrap_form_for @payment do |f| %>
      <div id="payment_container"></div>
      <%= f.number_field :amount, value: 1, min: 1, max: 9999, prepend: '$', append: '.00' %>
      <%= f.primary %>
    <% end %>
  </div>
</div>
<script>
  braintree.setup('<%= Braintree::ClientToken.generate %>', 'dropin', {
    container: 'payment_container'
  });
</script>

app/views/payments/show.html.erb
<%= render layout: 'shared/margins' do %>
  <h4>ID: <%= @payment.id %></h4>
  <h4>UUID: <%= @payment.uuid %></h4>
  <h4>Gateway: <%= @payment.gateway %></h4>
  <h4>State: <%= @payment.state %></h4>
<% end %>