config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  scope '/', defaults: { format: :html }, constraints: { format: :html } do
    delete 'users/stop_masquerading'
    resources :users, except: [:new] do
      post 'masquerade'
    end
    resources :groups
    resources :messages, only: :index
    resources :roles

    post 'payment_processor/paypal' => 'payment_processor#paypal'
    resources :payments, only: [:new, :create, :show, :index]
    get 'login' => 'login#index'
    post 'login' => 'login#verify'
    delete 'login' => 'login#logout'
  end

  scope :api, defaults: { format: :json }, constraints: { format: :json } do
    scope :v1 do
      resources :group_memberships, only: [:destroy, :create, :update]
      resources :users, except: [:new, :edit] do
        get 'group_memberships' => 'users#group_memberships'
      end
      get 'messages/recipients' => 'messages#search_recipients'
      resources :messages, except: [:new, :edit]
      resources :groups, except: [:new, :edit] do
        get 'potential_applicants' => 'groups#potential_applicants'
        get 'users' => 'groups#users'
        delete 'users' => 'group_memberships#destroy'
        put 'users' => 'group_memberships#create'
      end
      resources :roles, except: [:new, :edit] do
        get 'users' => 'roles#users'
        resources :role_memberships, only: [:create, :destroy]
      end

      resources :payments, only: [:index]
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_memberships, -> { active }
  has_many :users, -> { active }, through: :role_memberships

  validates :name, uniqueness: true, presence: true
  validates_inclusion_of :state, in: %w(active), if: :protected?

  serialize :permissions, Hash

  scope :active, -> { where(state: :active) }

  PERMISSION_TYPES = [
    { name: :manage_roles, component: :roles, description: 'Allows a user to create/edit/delete roles' },
    { name: :assign_roles, component: :roles, description: 'Allows a user to assign users to roles' },
    { name: :become_users, component: :users, description: 'Allows a user to become another user, and see things as they would' }
  ]

  after_initialize do
    Role::PERMISSION_TYPES.each do |k, v|
      permissions[k[:name]] ||= false
    end
    if protection_type == 'administrator'
      permissions.each do |k, v|
        permissions[k] = true
      end
    end
    permissions.symbolize_keys!
    permissions.transform_values! { |x| ['1', 1, 't', true].include?(x) }
  end

  before_validation do
    self.state ||= :active
  end

  def destroy
    self.state = :deleted
    save
  end

  def protected?
    !!protection_type
  end
  alias :protected :protected?

  def add_user(user)
    rp = RoleMembership.find_or_create_by(role: self, user: user)
    rp.update state: :active
    rp
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include PaginationHelper
  include Api::V1::User
  include Api::V1::Role
  include Api::V1::RoleMembership

  before_action :find_role, only: [:show, :edit, :update, :destroy, :users]
  before_action :find_roles, only: [:index, :show]
  load_and_authorize_resource

  def find_role
    @role = Role.active.find params[:id] || params[:role_id]
  end

  def find_roles
    @roles = Role.active
  end

  def index
    respond_to do |format|
      format.json do
        render json: pagination_json(@roles, :roles_json), status: :ok
      end
      format.html
    end
  end

  def create
    update_permissions
    respond_to do |format|
      format.html do
        if @role.save
          flash[:success] = 'Role created!'
          redirect_to @role
        else
          render 'new'
        end
      end
      format.json do
        if @role.save
          render json: role_json(@role), status: :ok
        else
          render json: { errors: @role.errors.full_messages }, status: :bad_request
        end
      end
    end
  end

  def update
    update_permissions
    respond_to do |format|
      format.html do
        if @role.update role_params
          flash[:success] = 'Role updated!'
          redirect_to @role
        else
          render 'edit'
        end
      end
      format.json do
        if @role.update role_params
          render json: role_json(@role), status: :ok
        else
          render json: { errors: @role.errors.full_messages }, status: :bad_request
        end
      end
    end
  end

  def update_permissions
    @role.permissions.clear
    return unless params[:permissions]
    Role::PERMISSION_TYPES.each do |p|
      @role.permissions[p[:name]] = params[:permissions][p[:name]]
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Role deleted!'
        redirect_to roles_path
      end
      format.json do
        render nothing: true, status: :no_content
      end
    end
  end

  def users
    authorize! :read, @role
    @rms = @role.role_memberships.includes(:user)
    respond_to do |format|
      format.json do
        render json: pagination_json(@rms, :role_memberships_json), status: :ok
      end
    end
  end

  private
  def role_params
    params.require(:role).permit(:name)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= bootstrap_form_for @role, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-8' do |g| %>
  <%= g.text_field :name %>
  <div class="col-sm-8 col-sm-offset-2">
    <div class="row">
      <% Role::PERMISSION_TYPES.map { |a| a[:component] }.uniq.each do |p| %>
        <div class="panel panel-default horizontal-form-margin">
          <div class="panel-heading"><%= p.capitalize %></div>
          <div class="panel-body">
            <div class="row">
              <% Role::PERMISSION_TYPES.select { |a| a[:component] == p }.each do |n| %>
                <div class="col-sm-4">
                  <span data-toggle="tooltip" data-placement="top" title="<%= n[:description] %>">
                    <%= check_box_tag "permissions[#{n[:name]}]", 1, @role.permissions[n[:name]] %>
                    <label for="permissions_<%= n[:name] %>"><%= n[:name].to_s.titleize %></label>
                  </span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-offset-2 col-sm-4" style="padding-left: 5px;">
    <%= g.primary %>
  </div>
<% end %>

app/views/roles/_name_and_navs.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4><%= @role.name %></h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-pills">
      <li role="presentation" class="<%= 'active' if params[:action] == 'show' %>">
        <a href="#role_permissions" data-toggle="tab">Permissions</a>
      </li>
      <li role="presentation" class="<%= 'active' if params[:action] == 'users' %>">
        <a href="#role_users" data-toggle="tab">Users</a>
      </li>
    </ul>
  </div>
</div>

app/views/roles/_roles_sidebar.html.erb
<div class="list-group">
  <% @roles.each do |g| %>
    <div class="list-group-item <%= 'active' if @role && @role == g %>">
      <%= link_to g.name, g, class: 'list-link' %>
      <% if can?(:update, g) %>
        <div class="dropdown pull-right">
          <i class="fa fa-cog group-list-item dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu navbar-default" role="menu">
            <li>
              <%= link_to edit_role_path(g) do %>
                <i class="fa fa-pencil"></i>
                Edit
              <% end %>
            </li>
            <li>
              <%= link_to role_path(g), method: :delete, data: { confirm: 'Are you sure you want to delete this role?' } do %>
                <i class="fa fa-trash-o"></i>
                Delete
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'New Role', new_role_path, class: 'btn btn-primary' if can?(:create, Role) %>

app/views/roles/_show_permissions.html.erb
<% Role::PERMISSION_TYPES.map { |a| a[:component] }.uniq.each do |p| %>
  <div class="panel panel-default">
    <div class="panel-heading"><%= p.capitalize %></div>
    <div class="panel-body">
      <div class="row">
        <% Role::PERMISSION_TYPES.select { |a| a[:component] == p }.each do |n| %>
          <div class="col-sm-4">
            <span data-toggle="tooltip" data-placement="top" title="<%= n[:description] %>">
              <i class="fa fa-<%= @role.permissions[n[:name].to_sym] ? 'check checked' : 'times times' %>"></i>
              <label><%= n[:name].to_s.titleize %></label>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/roles/_users_template.html.erb
<script type="text/x-handlebars-template" id="role_users_template">
  <div class="list-group-item">
    <div class="row">
      <div class="col-md-9">
        <a href="/users/{{id}}">
          <h4 class="list-group-item-heading">{{name}}</h4>
        </a>
        <p class="list-group-item-text">Added: {{date}}</p>
      </div>
      <div class="col-md-3">
        {{#if can_assign_roles}}
          <div class="pull-right dropdown">
            <i class="fa fa-cog group-list-item dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu navbar-default" role="menu">
              <li>
                <a href="#" name="remove-user-from-role" data-role-membership-id="{{membership_id}}">
                  <i class="fa fa-trash-o"></i>
                  Remove User
                </a>
              </li>
            </ul>
          </div>
        {{/if}}
      </div>
    </div>
  </div>
</script>

app/views/roles/edit.html.erb
<%= render partial: 'form' %>

app/views/roles/index.html.erb
<div class="row slight-margins">
  <div class="col-sm-3">
    <%= render partial: 'roles_sidebar' %>
  </div>
</div>

app/views/roles/new.html.erb
<%= render partial: 'form' %>

app/views/roles/show.html.erb
<div class="row slight-margins">
  <div class="col-sm-3">
    <%= render partial: 'roles_sidebar' %>
  </div>
  <div class="col-sm-9">
    <%= render partial: 'name_and_navs' %>
    <br>
    <div class="row">
      <div class="col-sm-12" role="tabpanel">
        <div class="tab-content">
          <div class="tab-pane active" id="role_permissions">
            <%= render partial: 'show_permissions' %>
          </div>
          <div class="tab-pane" id="role_users">
            <div class="no-bottom-margin list-group">

            </div>
            <ul class="pagination" id="role_users_pagination"></ul>
          </div>
        </div>
      </div>
    </div>
    <% if can? :manage, RoleMembership %>
      <button class="btn btn-primary" data-toggle="modal" data-target="#add_user_to_role_modal">Add User</button>
      <div class="modal fade" id="add_user_to_role_modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">Add User to <%= @role.name %></div>
            <div class="modal-body">
              <%= bootstrap_form_tag url: '#' do |f| %>
                <%= f.text_field :user, label: 'Start typing a user to be added' %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" data-dismiss="modal">Close</button>
              <button class="btn btn-primary" name="add-user-to-role">Add User</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="spacer"></div>
  </div>
  <%= render partial: 'users_template' %>
</div>