config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  scope '/', defaults: { format: :html }, constraints: { format: :html } do
    delete 'users/stop_masquerading'
    resources :users, except: [:new] do
      post 'masquerade'
    end
    resources :groups
    resources :messages, only: :index
    resources :roles

    post 'payment_processor/paypal' => 'payment_processor#paypal'
    resources :payments, only: [:new, :create, :show, :index]
    get 'login' => 'login#index'
    post 'login' => 'login#verify'
    delete 'login' => 'login#logout'
  end

  scope :api, defaults: { format: :json }, constraints: { format: :json } do
    scope :v1 do
      resources :group_memberships, only: [:destroy, :create, :update]
      resources :users, except: [:new, :edit] do
        get 'group_memberships' => 'users#group_memberships'
      end
      get 'messages/recipients' => 'messages#search_recipients'
      resources :messages, except: [:new, :edit]
      resources :groups, except: [:new, :edit] do
        get 'potential_applicants' => 'groups#potential_applicants'
        get 'users' => 'groups#users'
        delete 'users' => 'group_memberships#destroy'
        put 'users' => 'group_memberships#create'
      end
      resources :roles, except: [:new, :edit] do
        get 'users' => 'roles#users'
        resources :role_memberships, only: [:create, :destroy]
      end

      resources :payments, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsB</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>


  <script type="text/javascript">
      ENV = {
          current_user: <%= logged_in? ? @current_user.id : nil %>,
          permissions: {
              <% if logged_in? %>
              <% Role::PERMISSION_TYPES.each do |p| %>
              <%= (p[:name].to_s + ': ' + @current_user.has_permission?(p[:name]).to_s) + ', ' %>
              <% end %>
              <% end %>
          }
      };
  </script>
</head>
<body class="<%= params[:controller] %> <%= params[:action] %>">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SportsB', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% if masquerading? %>
            <li>
              <%= link_to 'Stop Masquerading', users_stop_masquerading_path, method: :delete %>
            </li>
          <% end %>
          <li><%= link_to messages_path do %>
            Messages
            <% count = @current_user.all_messages.unread.count %>
            <% if count > 0 %>
              <span class="badge"><%= count %></span>
            <% end %>
          <% end %></li>
          <li class="dropdown">
            <a type="button" data-toggle="dropdown" href="#">
              <span class="logged-in-user"><%= @current_user.display_name %></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu navbar-default" role="menu">
              <li><%= link_to 'My Profile', user_path(@current_user) %></li>
              <li><%= link_to 'Payments', payments_path %></li>
              <li><%= link_to 'Logout', login_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= flash_messages %>
</div>
<%= yield %>

</body>
</html>